# Generated by Django 5.2.17 on 2026-09-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('left', 'Left'), ('right', 'Right')], max_length=10, null=True),
        ),
    ]
